name: Deploy Hawkduty
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment target environment'
        required: true
        default: stage
        type: choice
        options:
          - stage
          - production
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Set up variables
      id: vars
      run: |
        if [ "${{ github.event.inputs.environment }}" = "production" ]; then
          echo "dir=/var/www/production/hawkduty.com" >> "$GITHUB_OUTPUT"
          echo "branch=main" >> "$GITHUB_OUTPUT"
        else
          echo "dir=/var/www/stage/oncall.elevatitech.com" >> "$GITHUB_OUTPUT"
          echo "branch=development" >> "$GITHUB_OUTPUT"
        fi
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        port: 22
        script: |
          cd ${{ steps.vars.outputs.dir }}
          git pull origin ${{ steps.vars.outputs.branch }}
          composer install --no-dev
          npm install
          npm run build
          sudo systemctl restart php8.2-fpm
          php artisan tenants:migrate
