name: Hawkduty Deploy to Staging or Production

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose Deployment environment'
        required: true
        default: 'staging'
        type: choice
        options: 
          - staging
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to ${{ github.event.inputs.environment }}

    steps:
    - name: select deploy directory
      id: set-dir
      run: |
        ENVIRONMENT=${{ github.event.inputs.environment }}
        if [ "$ENVIRONMENT" = "production"]; then
          echo "dir=/var/www/production/hawkduty.com" >> $GITHUB_OUTPUT
        else
          echo "dir=/var/www/stage/oncall.elevatitech.com" >> $GITHUB_OUTPUT
        fi
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with: 
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        script: |
          cd ${{  steps.set-dir.outputs.dir  }}
          git pull origin main
          composer install --no-dev
          cd backend
          npm install
          npm run prod 
          php artisan tenants:migrate
          sudo systemctl restart php8.2-fpm.service 
